### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Tranquility007** [songbingze/MLFF-GAN#2]
Could you provide a download link for the dataset used in this experiment?I would appreciate it very much.

**Comment by songbingze** [comment]
Hello!
You can use the following links to download the CIA and LGC datasets:
CIA Dataset: [http://dx.doi.org/10.4225/08/5111AC0BF1229](http://dx.doi.org/10.4225/08/5111AC0BF1229)
LGC Dataset: [http://dx.doi.org/10.4225/08/5111AD2B7FEE6](http://dx.doi.org/10.4225/08/5111AD2B7FEE6)
I have personally tested both links, and they are functional for downloading the datasets. If you have any further questions or need assistance regarding the dataset, please feel free to leave a comment.
