### ISSUE TITLE
data format conversion

### ISSUE THREAD

**Issue by DJWCBzy** [songbingze/MLFF-GAN#3]
Hello, what method did you use to convert the int and bil format files in the data set into tif format?

**Comment by songbingze** [comment]
Hi!

The key points for handling these two types of files are the instructions about the datasets found in the folders ('CIA_readme.txt' and 'LGC_readme.txt'). 

In the 'CIA_readme.txt' file, you can find references to the BSQ format and the BIL format on lines 45 and 66, respectively. Similarly, in the 'LGC_readme.txt' file, the BSQ format is mentioned on lines 45 and 69. These formats correspond to files with the '.int' and '.bil' extensions in both datasets. In addition to these two formats, there is another format called BIP that is commonly used in remote sensing images to store raster information. If you are interested, you can search the internet to learn more about these three data formats.

To read '.int' and '.bil' files, you can try using the NumPy library in Python. Here is the code snippet for reading the files:

For '.int' files:
```
bsq_image_data = np.fromfile("image_file_name.int", dtype=np.int16).reshape((num_bands, height, width)).transpose(1, 2, 0)
```

For '.bil' files:
```
bil_image_data = np.fromfile("image_file_name.bil", dtype=np.int16).reshape((height, num_bands, width)).transpose(0, 2, 1)
```

You can find the height, width, and number of bands of the image in 'CIA_readme.txt' and 'LGC_readme.txt'.

I have tested these code snippets on two images from the CIA dataset, and they successfully read the images into matrices of shape (height, width, num_bands). You can use other methods to convert them into the .tif image file format.

Please note that the data types for both formats are signed 16-bit integers, and the invalid value is -9999. For more specific information, you can refer to the USGS documentation on MODIS and Landsat surface reflectance products.

If you have any other questions regarding file reading and conversion, feel free to ask.

**Comment by Sofianebouaziz1** [comment]
Hi!
Thank you for the detailed explanation on how to handle the CIA and LGC datasets.

I have a couple of follow-up questions:
1. Could you please provide the specific script you used to preprocess the data for both the CIA and LGC datasets? 
2. Could you also share how you created and organized the data folder structure for both datasets? 

Thanks again for your support!
