### ISSUE TITLE
image_size

### ISSUE THREAD

**Issue by DJWCBzy** [songbingze/MLFF-GAN#5]
Hello, the run.py program you provided set image_size as [1792,1280], but the image size in the actual CIA data set is [2040,1720], so I would like to ask how [1792,1280] is calculated and why it is set to this size. What to set when using the LGC data set? Thank you!

**Comment by songbingze** [comment]
The code is designed to handle images of size 256*m and 256*n, where m and n are positive integers. After processing, you can concatenate the images together.
