### ISSUE TITLE
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by paul623** [songbingze/MLFF-GAN#6]
First of all, thank you very much for sharing your model's pretraining .pth files. However, I find that it is not working well.
Please check if files are damaged.
Traceback (most recent call last):
  File "/home/user/codeLab/remotePython/MLFF-GAN/run.py", line 94, in <module>
    experiment.test(test_dir, opt.image_size, opt.patch_size, num_workers=opt.num_workers)
  File "/home/user/anaconda3/envs/d2l/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/codeLab/remotePython/MLFF-GAN/experiment.py", line 295, in test
    load_checkpoint(self.best, model=self.generator)
  File "/home/user/codeLab/remotePython/MLFF-GAN/utils.py", line 69, in load_checkpoint
    state = torch.load(checkpoint, map_location=map_location)
  File "/home/user/anaconda3/envs/d2l/lib/python3.9/site-packages/torch/serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/user/anaconda3/envs/d2l/lib/python3.9/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by songbingze** [comment]
I have re-uploaded the available model. 
However, due to its age, there may be some unexpected errors. Feel free to contact me if any arise.
If necessary, I can reproduce the experiment, but that will take some time.

**Comment by paul623** [comment]
Thanks a lot！

**Comment by paul623** [comment]
The .pth file you provided is now complete, but there seems to be an issue with the mismatch of weight names, which likely occurred due to changes you made to the model later on. 
Currently, the problem I'm facing is that after retraining your model, it performs optimally on the LGC dataset, but not on CIA. The average SSIM (Structural Similarity Index Measure) score for CIA is only around 70, and I'm unsure if the CIA dataset has undergone any specific processing (such as cropping).
Here is my CIA dataset：
![image](https://github.com/songbingze/MLFF-GAN/assets/42802245/9f165092-f7e5-4c2d-9a77-012a734e104c)
And my trained model：
链接：https://pan.baidu.com/s/1Js4aKWayUQdEq9M0ZUEHxQ?pwd=yunh 
提取码：yunh

**Comment by paul623** [comment]
RuntimeError: Error(s) in loading state_dict for CombinFeatureGenerator:
	Missing key(s) in state_dict: "LSNet.conv1.0.weight", "LSNet.conv1.0.bias", "LSNet.conv1.1.residual.1.weight", "LSNet.conv1.1.residual.1.bias", "LSNet.conv1.1.residual.5.weight", "LSNet.conv1.1.residual.5.bias", "LSNet.conv2.0.weight", "LSNet.conv2.0.bias", "LSNet.conv2.1.residual.1.weight", "LSNet.conv2.1.residual.1.bias", "LSNet.conv2.1.residual.5.weight", "LSNet.conv2.1.residual.5.bias", "LSNet.conv3.0.weight", "LSNet.conv3.0.bias", "LSNet.conv3.1.residual.1.weight", "LSNet.conv3.1.residual.1.bias", "LSNet.conv3.1.residual.5.weight", "LSNet.conv3.1.residual.5.bias", "LSNet.conv4.0.weight", "LSNet.conv4.0.bias", "LSNet.conv4.1.residual.1.weight", "LSNet.conv4.1.residual.1.bias", "LSNet.conv4.1.residual.5.weight", "LSNet.conv4.1.residual.5.bias", "LSNet.conv5.0.weight", "LSNet.conv5.0.bias", "LSNet.conv5.1.residual.1.weight", "LSNet.conv5.1.residual.1.bias", "LSNet.conv5.1.residual.5.weight", "LSNet.conv5.1.residual.5.bias", "HSNet.conv1.0.weight", "HSNet.conv1.0.bias", "HSNet.conv1.1.residual.1.weight", "HSNet.conv1.1.residual.1.bias", "HSNet.conv1.1.residual.5.weight", "HSNet.conv1.1.residual.5.bias", "HSNet.conv2.0.weight", "HSNet.conv2.0.bias", "HSNet.conv2.1.residual.1.weight", "HSNet.conv2.1.residual.1.bias", "HSNet.conv2.1.residual.5.weight", "HSNet.conv2.1.residual.5.bias", "HSNet.conv3.0.weight", "HSNet.conv3.0.bias", "HSNet.conv3.1.residual.1.weight", "HSNet.conv3.1.residual.1.bias", "HSNet.conv3.1.residual.5.weight", "HSNet.conv3.1.residual.5.bias", "HSNet.conv4.0.weight", "HSNet.conv4.0.bias", "HSNet.conv4.1.residual.1.weight", "HSNet.conv4.1.residual.1.bias", "HSNet.conv4.1.residual.5.weight", "HSNet.conv4.1.residual.5.bias", "HSNet.conv5.0.weight", "HSNet.conv5.0.bias", "HSNet.conv5.1.residual.1.weight", "HSNet.conv5.1.residual.1.bias", "HSNet.conv5.1.residual.5.weight", "HSNet.conv5.1.residual.5.bias", "SignE_List.0.conv1.0.weight", "SignE_List.0.conv1.0.bias", "SignE_List.0.conv1.1.weight", "SignE_List.0.conv1.1.bias", "SignE_List.0.conv1.1.running_mean", "SignE_List.0.conv1.1.running_var", "SignE_List.0.conv2.0.weight", "SignE_List.0.conv2.0.bias", "SignE_List.0.conv2.1.weight", "SignE_List.0.conv2.1.bias", "SignE_List.0.conv2.1.running_mean", "SignE_List.0.conv2.1.running_var", "SignE_List.0.conv.0.weight", "SignE_List.0.conv.0.bias", "SignE_List.0.conv.1.weight", "SignE_List.0.conv.1.bias", "SignE_List.0.conv.1.running_mean", "SignE_List.0.conv.1.running_var", "SignE_List.1.conv1.0.weight", "SignE_List.1.conv1.0.bias", "SignE_List.1.conv1.1.weight", "SignE_List.1.conv1.1.bias", "SignE_List.1.conv1.1.running_mean", "SignE_List.1.conv1.1.running_var", "SignE_List.1.conv2.0.weight", "SignE_List.1.conv2.0.bias", "SignE_List.1.conv2.1.weight", "SignE_List.1.conv2.1.bias", "SignE_List.1.conv2.1.running_mean", "SignE_List.1.conv2.1.running_var", "SignE_List.1.conv.0.weight", "SignE_List.1.conv.0.bias", "SignE_List.1.conv.1.weight", "SignE_List.1.conv.1.bias", "SignE_List.1.conv.1.running_mean", "SignE_List.1.conv.1.running_var", "SignE_List.2.conv1.0.weight", "SignE_List.2.conv1.0.bias", "SignE_List.2.conv1.1.weight", "SignE_List.2.conv1.1.bias", "SignE_List.2.conv1.1.running_mean", "SignE_List.2.conv1.1.running_var", "SignE_List.2.conv2.0.weight", "SignE_List.2.conv2.0.bias", "SignE_List.2.conv2.1.weight", "SignE_List.2.conv2.1.bias", "SignE_List.2.conv2.1.running_mean", "SignE_List.2.conv2.1.running_var", "SignE_List.2.conv.0.weight", "SignE_List.2.conv.0.bias", "SignE_List.2.conv.1.weight", "SignE_List.2.conv.1.bias", "SignE_List.2.conv.1.running_mean", "SignE_List.2.conv.1.running_var", "SignE_List.3.conv1.0.weight", "SignE_List.3.conv1.0.bias", "SignE_List.3.conv1.1.weight", "SignE_List.3.conv1.1.bias", "SignE_List.3.conv1.1.running_mean", "SignE_List.3.conv1.1.running_var", "SignE_List.3.conv2.0.weight", "SignE_List.3.conv2.0.bias", "SignE_List.3.conv2.1.weight", "SignE_List.3.conv2.1.bias", "SignE_List.3.conv2.1.running_mean", "SignE_List.3.conv2.1.running_var", "SignE_List.3.conv.0.weight", "SignE_List.3.conv.0.bias", "SignE_List.3.conv.1.weight", "SignE_List.3.conv.1.bias", "SignE_List.3.conv.1.running_mean", "SignE_List.3.conv.1.running_var", "SignE_List.4.conv1.0.weight", "SignE_List.4.conv1.0.bias", "SignE_List.4.conv1.1.weight", "SignE_List.4.conv1.1.bias", "SignE_List.4.conv1.1.running_mean", "SignE_List.4.conv1.1.running_var", "SignE_List.4.conv2.0.weight", "SignE_List.4.conv2.0.bias", "SignE_List.4.conv2.1.weight", "SignE_List.4.conv2.1.bias", "SignE_List.4.conv2.1.running_mean", "SignE_List.4.conv2.1.running_var", "SignE_List.4.conv.0.weight", "SignE_List.4.conv.0.bias", "SignE_List.4.conv.1.weight", "SignE_List.4.conv.1.bias", "SignE_List.4.conv.1.running_mean", "SignE_List.4.conv.1.running_var", "conv1.0.deconv.weight", "conv1.0.deconv.bias", "conv1.1.residual.1.weight", "conv1.1.residual.1.bias", "conv1.1.residual.5.weight", "conv1.1.residual.5.bias", "conv2.0.deconv.weight", "conv2.0.deconv.bias", "conv2.1.residual.1.weight", "conv2.1.residual.1.bias", "conv2.1.residual.5.weight", "conv2.1.residual.5.bias", "conv3.0.deconv.weight", "conv3.0.deconv.bias", "conv3.1.residual.1.weight", "conv3.1.residual.1.bias", "conv3.1.residual.5.weight", "conv3.1.residual.5.bias", "conv4.0.deconv.weight", "conv4.0.deconv.bias", "conv4.1.residual.1.weight", "conv4.1.residual.1.bias", "conv4.1.residual.5.weight", "conv4.1.residual.5.bias", "conv5.0.residual.1.weight", "conv5.0.residual.1.bias", "conv5.0.residual.5.weight", "conv5.0.residual.5.bias", "conv5.1.weight", "conv5.1.bias", "conv5.2.residual.1.weight", "conv5.2.residual.1.bias", "conv5.2.residual.5.weight", "conv5.2.residual.5.bias", "conv5.3.weight", "conv5.3.bias". 
	Unexpected key(s) in state_dict: "LSNet1.conv1.residual.0.1.weight", "LSNet1.conv1.residual.0.1.bias", "LSNet1.conv1.residual.2.weight", "LSNet1.conv1.residual.2.bias", "LSNet1.conv1.transform.weight", "LSNet1.conv1.transform.bias", "LSNet1.conv2.residual.0.1.weight", "LSNet1.conv2.residual.0.1.bias", "LSNet1.conv2.residual.2.weight", "LSNet1.conv2.residual.2.bias", "LSNet1.conv2.transform.weight", "LSNet1.conv2.transform.bias", "LSNet1.conv3.residual.0.1.weight", "LSNet1.conv3.residual.0.1.bias", "LSNet1.conv3.residual.2.weight", "LSNet1.conv3.residual.2.bias", "LSNet1.conv3.transform.weight", "LSNet1.conv3.transform.bias", "LSNet1.conv4.residual.0.1.weight", "LSNet1.conv4.residual.0.1.bias", "LSNet1.conv4.residual.2.weight", "LSNet1.conv4.residual.2.bias", "LSNet1.conv4.transform.weight", "LSNet1.conv4.transform.bias", "LSNet1.conv5.residual.0.1.weight", "LSNet1.conv5.residual.0.1.bias", "LSNet1.conv5.residual.2.weight", "LSNet1.conv5.residual.2.bias", "LSNet1.conv5.transform.weight", "LSNet1.conv5.transform.bias", "LSNet2.conv1.residual.0.1.weight", "LSNet2.conv1.residual.0.1.bias", "LSNet2.conv1.residual.2.weight", "LSNet2.conv1.residual.2.bias", "LSNet2.conv1.transform.weight", "LSNet2.conv1.transform.bias", "LSNet2.conv2.residual.0.1.weight", "LSNet2.conv2.residual.0.1.bias", "LSNet2.conv2.residual.2.weight", "LSNet2.conv2.residual.2.bias", "LSNet2.conv2.transform.weight", "LSNet2.conv2.transform.bias", "LSNet2.conv3.residual.0.1.weight", "LSNet2.conv3.residual.0.1.bias", "LSNet2.conv3.residual.2.weight", "LSNet2.conv3.residual.2.bias", "LSNet2.conv3.transform.weight", "LSNet2.conv3.transform.bias", "LSNet2.conv4.residual.0.1.weight", "LSNet2.conv4.residual.0.1.bias", "LSNet2.conv4.residual.2.weight", "LSNet2.conv4.residual.2.bias", "LSNet2.conv4.transform.weight", "LSNet2.conv4.transform.bias", "LSNet2.conv5.residual.0.1.weight", "LSNet2.conv5.residual.0.1.bias", "LSNet2.conv5.residual.2.weight", "LSNet2.conv5.residual.2.bias", "LSNet2.conv5.transform.weight", "LSNet2.conv5.transform.bias", "HSNet3.conv1.residual.0.1.weight", "HSNet3.conv1.residual.0.1.bias", "HSNet3.conv1.residual.2.weight", "HSNet3.conv1.residual.2.bias", "HSNet3.conv1.transform.weight", "HSNet3.conv1.transform.bias", "HSNet3.conv2.residual.0.1.weight", "HSNet3.conv2.residual.0.1.bias", "HSNet3.conv2.residual.2.weight", "HSNet3.conv2.residual.2.bias", "HSNet3.conv2.transform.weight", "HSNet3.conv2.transform.bias", "HSNet3.conv3.residual.0.1.weight", "HSNet3.conv3.residual.0.1.bias", "HSNet3.conv3.residual.2.weight", "HSNet3.conv3.residual.2.bias", "HSNet3.conv3.transform.weight", "HSNet3.conv3.transform.bias", "HSNet3.conv4.residual.0.1.weight", "HSNet3.conv4.residual.0.1.bias", "HSNet3.conv4.residual.2.weight", "HSNet3.conv4.residual.2.bias", "HSNet3.conv4.transform.weight", "HSNet3.conv4.transform.bias", "HSNet3.conv5.residual.0.1.weight", "HSNet3.conv5.residual.0.1.bias", "HSNet3.conv5.residual.2.weight", "HSNet3.conv5.residual.2.bias", "HSNet3.conv5.transform.weight", "HSNet3.conv5.transform.bias", "conv1.residual.1.1.weight", "conv1.residual.1.1.bias", "conv1.residual.3.weight", "conv1.residual.3.bias", "conv1.transform.1.weight", "conv1.transform.1.bias", "conv2.residual.1.1.weight", "conv2.residual.1.1.bias", "conv2.residual.3.weight", "conv2.residual.3.bias", "conv2.transform.1.weight", "conv2.transform.1.bias", "conv3.residual.1.1.weight", "conv3.residual.1.1.bias", "conv3.residual.3.weight", "conv3.residual.3.bias", "conv3.transform.1.weight", "conv3.transform.1.bias", "conv4.residual.1.1.weight", "conv4.residual.1.1.bias", "conv4.residual.3.weight", "conv4.residual.3.bias", "conv4.transform.1.weight", "conv4.transform.1.bias", "conv5.residual.0.1.weight", "conv5.residual.0.1.bias", "conv5.residual.2.weight", "conv5.residual.2.bias", "conv5.transform.weight", "conv5.transform.bias". 

Process finished with exit code 1

**Comment by songbingze** [comment]
Based on my inference from the results you provided, you can explore the following aspects to identify the problem:

1.Some images in the CIA dataset contain invalid values, denoted as -9999. I think these should not be included in the calculations. In my metric calculations, I disregard the parts of the images from the reference and prediction times that contain invalid values. 
2.Are all images performing poorly, or is it only specific ones? If it's specific images, it might be due to the reason mentioned in point 1. If all images are performing poorly, please verify if the experimental conditions for multiple models are the same.
3.If neither of the above scenarios is true, and if needed, I can retrain the model within two months and provide you with test results.

Please feel free to stay in touch if there are any other issues.

**Comment by paul623** [comment]
> Based on my inference from the results you provided, you can explore the following aspects to identify the problem:
> 
> 1.Some images in the CIA dataset contain invalid values, denoted as -9999. I think these should not be included in the calculations. In my metric calculations, I disregard the parts of the images from the reference and prediction times that contain invalid values. 2.Are all images performing poorly, or is it only specific ones? If it's specific images, it might be due to the reason mentioned in point 1. If all images are performing poorly, please verify if the experimental conditions for multiple models are the same. 3.If neither of the above scenarios is true, and if needed, I can retrain the model within two months and provide you with test results.
> 
> Please feel free to stay in touch if there are any other issues.

Okay, I checked the CIA datasets and deleted all the illegal data, but it is still not working well. Can I add a contact number or something, if that's okay

**Comment by songbingze** [comment]
My e-mail: songbingze19@mails.ucas.ac.cn.
